### ISSUE TITLE
TO-DO in P1: vagrant & ansible

### ISSUE THREAD

**Issue by pabloqpacin** [pabloqpacin/devops_101#4]
- [ ] Vagrant snapshots
  - [ ] https://developer.hashicorp.com/vagrant/docs/cli/snapshot
- [ ] GitHub Actions for Ansible
  - [ ] https://github.com/marketplace/actions/run-ansible-lint
- [ ] Password & Token Security
  - [ ] Ansible Vault
